//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int CheckOutID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> MagazineID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string CheckInDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Magazine Magazine { get; set; }
    }
}
